name = "ttcalc-photo-proxy"
main = "worker/index.js"
compatibility_date = "2026-08-01"

[[kv_namespaces]]
binding = "PHOTO_QUOTA"
id = "b7e69333a0054e81868ec477c76fbf1e"

[vars]
PHOTO_GLOBAL_DAILY_LIMIT = "50"
